/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: it@vilabs.eu
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Product from './Product';
import UserUserimage from './UserUserimage';

/**
 * The User model module.
 * @module model/User
 * @version 1.0.0
 */
class User {
    /**
     * Constructs a new <code>User</code>.
     * @alias module:model/User
     * @param useremail {String} 
     * @param password {String} 
     * @param username {String} 
     * @param usercategory {String} 
     * @param userstatus {String} 
     * @param userimage {module:model/UserUserimage} 
     * @param mondayclose {String} 
     * @param mondayopen {String} 
     * @param tuesdayopen {String} 
     * @param tuesdayclose {String} 
     * @param wednesdayopen {String} 
     * @param wednesdayclose {String} 
     * @param thursdayclose {String} 
     * @param thursdayopen {String} 
     * @param fridayopen {String} 
     * @param fridayclose {String} 
     * @param usertown {String} 
     * @param userregion {String} 
     * @param useraddress {String} 
     * @param userpc {Number} 
     * @param userproducts {Array.<module:model/Product>} 
     */
    constructor(useremail, password, username, usercategory, userstatus, userimage, mondayclose, mondayopen, tuesdayopen, tuesdayclose, wednesdayopen, wednesdayclose, thursdayclose, thursdayopen, fridayopen, fridayclose, usertown, userregion, useraddress, userpc, userproducts) { 
        
        User.initialize(this, useremail, password, username, usercategory, userstatus, userimage, mondayclose, mondayopen, tuesdayopen, tuesdayclose, wednesdayopen, wednesdayclose, thursdayclose, thursdayopen, fridayopen, fridayclose, usertown, userregion, useraddress, userpc, userproducts);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, useremail, password, username, usercategory, userstatus, userimage, mondayclose, mondayopen, tuesdayopen, tuesdayclose, wednesdayopen, wednesdayclose, thursdayclose, thursdayopen, fridayopen, fridayclose, usertown, userregion, useraddress, userpc, userproducts) { 
        obj['useremail'] = useremail;
        obj['password'] = password;
        obj['username'] = username;
        obj['usercategory'] = usercategory;
        obj['userstatus'] = userstatus;
        obj['userimage'] = userimage;
        obj['mondayclose'] = mondayclose;
        obj['mondayopen'] = mondayopen;
        obj['tuesdayopen'] = tuesdayopen;
        obj['tuesdayclose'] = tuesdayclose;
        obj['wednesdayopen'] = wednesdayopen;
        obj['wednesdayclose'] = wednesdayclose;
        obj['thursdayclose'] = thursdayclose;
        obj['thursdayopen'] = thursdayopen;
        obj['fridayopen'] = fridayopen;
        obj['fridayclose'] = fridayclose;
        obj['usertown'] = usertown;
        obj['userregion'] = userregion;
        obj['useraddress'] = useraddress;
        obj['userpc'] = userpc;
        obj['userproducts'] = userproducts;
    }

    /**
     * Constructs a <code>User</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/User} obj Optional instance to populate.
     * @return {module:model/User} The populated <code>User</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new User();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('useremail')) {
                obj['useremail'] = ApiClient.convertToType(data['useremail'], 'String');
            }
            if (data.hasOwnProperty('password')) {
                obj['password'] = ApiClient.convertToType(data['password'], 'String');
            }
            if (data.hasOwnProperty('username')) {
                obj['username'] = ApiClient.convertToType(data['username'], 'String');
            }
            if (data.hasOwnProperty('usercategory')) {
                obj['usercategory'] = ApiClient.convertToType(data['usercategory'], 'String');
            }
            if (data.hasOwnProperty('userstatus')) {
                obj['userstatus'] = ApiClient.convertToType(data['userstatus'], 'String');
            }
            if (data.hasOwnProperty('userimage')) {
                obj['userimage'] = UserUserimage.constructFromObject(data['userimage']);
            }
            if (data.hasOwnProperty('mondayclose')) {
                obj['mondayclose'] = ApiClient.convertToType(data['mondayclose'], 'String');
            }
            if (data.hasOwnProperty('mondayopen')) {
                obj['mondayopen'] = ApiClient.convertToType(data['mondayopen'], 'String');
            }
            if (data.hasOwnProperty('tuesdayopen')) {
                obj['tuesdayopen'] = ApiClient.convertToType(data['tuesdayopen'], 'String');
            }
            if (data.hasOwnProperty('tuesdayclose')) {
                obj['tuesdayclose'] = ApiClient.convertToType(data['tuesdayclose'], 'String');
            }
            if (data.hasOwnProperty('wednesdayopen')) {
                obj['wednesdayopen'] = ApiClient.convertToType(data['wednesdayopen'], 'String');
            }
            if (data.hasOwnProperty('wednesdayclose')) {
                obj['wednesdayclose'] = ApiClient.convertToType(data['wednesdayclose'], 'String');
            }
            if (data.hasOwnProperty('thursdayclose')) {
                obj['thursdayclose'] = ApiClient.convertToType(data['thursdayclose'], 'String');
            }
            if (data.hasOwnProperty('thursdayopen')) {
                obj['thursdayopen'] = ApiClient.convertToType(data['thursdayopen'], 'String');
            }
            if (data.hasOwnProperty('fridayopen')) {
                obj['fridayopen'] = ApiClient.convertToType(data['fridayopen'], 'String');
            }
            if (data.hasOwnProperty('fridayclose')) {
                obj['fridayclose'] = ApiClient.convertToType(data['fridayclose'], 'String');
            }
            if (data.hasOwnProperty('usertown')) {
                obj['usertown'] = ApiClient.convertToType(data['usertown'], 'String');
            }
            if (data.hasOwnProperty('userregion')) {
                obj['userregion'] = ApiClient.convertToType(data['userregion'], 'String');
            }
            if (data.hasOwnProperty('useraddress')) {
                obj['useraddress'] = ApiClient.convertToType(data['useraddress'], 'String');
            }
            if (data.hasOwnProperty('userpc')) {
                obj['userpc'] = ApiClient.convertToType(data['userpc'], 'Number');
            }
            if (data.hasOwnProperty('userproducts')) {
                obj['userproducts'] = ApiClient.convertToType(data['userproducts'], [Product]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
User.prototype['_id'] = undefined;

/**
 * @member {String} useremail
 */
User.prototype['useremail'] = undefined;

/**
 * @member {String} password
 */
User.prototype['password'] = undefined;

/**
 * @member {String} username
 */
User.prototype['username'] = undefined;

/**
 * @member {String} usercategory
 */
User.prototype['usercategory'] = undefined;

/**
 * @member {String} userstatus
 */
User.prototype['userstatus'] = undefined;

/**
 * @member {module:model/UserUserimage} userimage
 */
User.prototype['userimage'] = undefined;

/**
 * @member {String} mondayclose
 */
User.prototype['mondayclose'] = undefined;

/**
 * @member {String} mondayopen
 */
User.prototype['mondayopen'] = undefined;

/**
 * @member {String} tuesdayopen
 */
User.prototype['tuesdayopen'] = undefined;

/**
 * @member {String} tuesdayclose
 */
User.prototype['tuesdayclose'] = undefined;

/**
 * @member {String} wednesdayopen
 */
User.prototype['wednesdayopen'] = undefined;

/**
 * @member {String} wednesdayclose
 */
User.prototype['wednesdayclose'] = undefined;

/**
 * @member {String} thursdayclose
 */
User.prototype['thursdayclose'] = undefined;

/**
 * @member {String} thursdayopen
 */
User.prototype['thursdayopen'] = undefined;

/**
 * @member {String} fridayopen
 */
User.prototype['fridayopen'] = undefined;

/**
 * @member {String} fridayclose
 */
User.prototype['fridayclose'] = undefined;

/**
 * @member {String} usertown
 */
User.prototype['usertown'] = undefined;

/**
 * @member {String} userregion
 */
User.prototype['userregion'] = undefined;

/**
 * @member {String} useraddress
 */
User.prototype['useraddress'] = undefined;

/**
 * @member {Number} userpc
 */
User.prototype['userpc'] = undefined;

/**
 * @member {Array.<module:model/Product>} userproducts
 */
User.prototype['userproducts'] = undefined;






export default User;

